on:
    push:

jobs:
  cache-test-build-only:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        key: test-build
        path: 'build'
    - run: |
        ls -l **
        make

  cache-test-all:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/cache/restore@v3
      with:
        key: test-all
        path: '.'
    - uses: actions/checkout@v3
    - run: |
        ls -l **
        make
    - uses: actions/cache/save@v3
      with:
        key: test-all
        path: '.'
