on:
  pull_request:
    types:
      - labeled

jobs:
  pr-label-sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Report failure from label
        if: github.event.pull_request.labels.name == 'private-check-failed'
        run: exit 1

      - name: Report success from label
        if: github.event.pull_request.labels.name == 'private-check-success'
        run: exit 0
