on:
  pull_request:
    types:
      - labeled

jobs:
  pr-label-sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Report failure from label
        run: |
          echo PR Tagged ${{ github.event.pull_request.labels.name }}
          if ${{ github.event.pull_request.labels.name }} = 'private-ci-success'; then
            exit 0
          else
            exit 1
          fi
